doctrine:
    orm:
        entity_managers:
            batch:
                connection: message_queue
                mappings:
                    OroBatchBundle:
                        mapping: true
                        is_bundle: true
                metadata_cache_driver:
                    type: service
                    id:   oro_batch.cache.doctrine_metadata
